### ISSUE TITLE
Prioritizer: throw an error when merging different data with identical priority

### ISSUE THREAD

**Issue by dmach** [fedora-modularity/libmodulemd#44] opened 2018-04-17 07:45 UTC
I'm not sure if it's expected that provided example ends with 'master' default stream.
I was assuming that this behavior is allowed only when 2nd record has higher priority (lower number).
Shouldn't the Prioritizer raise an error instead?

```
document: modulemd-defaults
version: 1
data:
  module: testmodule
  stream: 2.0
  profiles:
    master: [default]
---
document: modulemd-defaults
version: 1
data:
  module: testmodule
  stream: master
  profiles:
    master: [default]
```

**Comment by sgallagher** [comment] 2018-04-18 11:36
I think you misunderstood priority for modulemd. The *higher* number wins, not the lower.

However, if this isn't throwing an error, there must be a bug somewhere. I thought I had added a test for this case; I must have missed it.

**Comment by sgallagher** [comment] 2018-04-18 17:59
Ahhh, I see what happened here. The first document fails to parse successfully because it has no matching profile for the default stream (See https://github.com/fedora-modularity/libmodulemd/issues/43 for details on a change in plan for that).

The first document results in zero valid entries, so there's nothing with which to conflict for the second document, thus it wins. If you change the first document to be:
```
document: modulemd-defaults
version: 1
data:
  module: testmodule
  stream: 2.0
  profiles:
    master: [default]
    2.0: [default]
```
It correctly identifies a conflict and rejects the merge.

The decision to ignore documents that can't be read is there primarily for robustness (a single mistake by a module creator cannot break a compose), but it *can* lead to some unexpected behavior on merges, I suppose. The problem is that we really only have two choices on bad input: ignore the bad section or reject the entire stream.

**Comment by sgallagher** [comment] 2018-04-20 18:03
I think the underlying problem here was that the ignored document went unnoticed. That should be resolved with https://github.com/fedora-modularity/libmodulemd/issues/47 (and PR https://github.com/fedora-modularity/libmodulemd/pull/58) so I'm going to close this ticket.

**Closed by sgallagher** 2018-04-20 18:03 UTC
Labels: bug
