### ISSUE TITLE
implement "buildafter" or something similar for components/rpms

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#96] opened 2018-10-22 16:26 UTC
Only one of `buildorder` or `buildafter` should be used. Then MBS could take advantage of this submitting all builds at once and let koji handle build queue and priorities.

I picked first name which came to my mind, you can choose different one.

**Comment by contyk** [comment] 2018-10-23 18:49
Do you think just the notion of "after" would be sufficient or should there be other keywords, similar to the dependency language of systemd unit files, for instance?

By the way, this is tracked as a high level goal here: https://tree.taiga.io/project/modularity-wg/epic/33

**Comment by ignatenkobrain** [comment] 2018-10-23 22:46
hmmm, I think `after` should be enough.

**Comment by sgallagher** [comment] 2018-11-21 13:45
@contyk, @ignatenkobrain 
I gave this some thought this morning and I have a suggestion for how this might work. Here's an example of the structure (underneath the `data` section of modulemd and excluding the rest of the modulemd)

```yaml
components:
    rpms:
        myrpm:
            rationale: My RPM
            ref: master
            after: somedep
            bootstrap:
                first_pass:
                    buildopts:
                        rpms:
                            macros: <stuff>
                second_pass:
                    buildopts:
                        rpms:
                            macros: <more stuff>
                    after:
                        myrpm: first_pass
                        somedep: ""
                        someotherdep: ""                    
        somedep:
            rationale: Dep for myrpm
            ref: master
            after:
                myrpm: first_pass
        someotherdep:
            rationale: Needed to bootstrap rationale
            ref: master
```

To break it down, we'd add two new directives: `after` and `bootstrap`. We would replace `buildorder` with `after` (and I'd recommend we make this a metadata version bump so we can process upgrades from v2 rather than trying to have `buildorder` and `after` coexist. `after` is a YAML mapping whose keys are the names of other RPM components in this module and whose value is the name of the bootstrapping section (see below) they need to occur after. If they need to be ordered after the main RPM, the empty string should be used.

The second addition is the new `bootstrap` section. We can bikeshed on the name if we must, but the main reason one would want to build more than once is to handle bootstrapping situations, so it seemed like the right name to me. The idea is that if the bootstrap section is present, its builds must be performed before the main build is run. If there are multiple bootstrap steps, they can be named whatever makes sense and should be ordered using the same `after` directive.

The `bootstrap` section includes a `buildopts` subsection that follows the same semantics as the one for the general RPM. It is present so that the build can set bootstrapping-specific build macros. The expected behavior of the build should be that the output of `bootstrap` builds should go into the buildroot for the rest of the module build, but they should not end up in the final produced module. This is probably best handled by MBS automatically adding appropriate `filter` values.

Feedback highly-desired.

**Comment by sgallagher** [comment] 2018-12-11 01:31
@contyk @mprahl @hanzz I would very much appreciate input on this in the near future.

**Comment by ignatenkobrain** [comment] 2018-12-11 09:03
According to an example above, buildorder will be following:

* `someotherdep` is built at the same time as `myrpm/first_pass`
* once `myrpm/first_pass` is built, we start building `somedep`
* once both `somedep` and `someotherdep` are available, we start building `myrpm/second_pass`
* once `myrpm/second_pass` is built, we build `myrpm`

Do I understand this example correctly?

**Comment by sgallagher** [comment] 2019-01-23 14:05
@ignatenkobrain Sorry, I thought I replied to this, but I must not have. Yes, that is what I expect to happen there.

@mizdebsk this is the ticket I mentioned to you today.

**Comment by mizdebsk** [comment] 2019-01-24 11:14
The "after" functionality is a good generalization of buildorder and it would help to speed up some module builds. The "bootstrap" feature proposed by @sgallagher should work in some, but not all bootstrapping cases. Notably, it won't work for bootstrapping javapackages-tools module in Fedora.

**Comment by hanzz** [comment] 2019-02-08 14:04
I'm OK with buildafter, this is only syntax change from which we can still generate buildorder and use batches internally in MBS.

For bootstrap, there might be some implementation issues/decisions which we should discuss:

1) How to pass build macros to single Koji build? I think we currently set buildmacros in module-build-macros and with bootstrap, we would need to add a macro there, rebuild modul-build-macros, use it to build that single package and then untag module-build-macros. This will lead to serialization of the build process, because only single bootstrap package can be built using this way. Or maybe there is some other way how to achieve this?

2) There is NVR conflict between each phase of bootstrap build.

I would ideally like to see some document with example build and what the implementation is supposed to do, so we can all agree on that.

**Comment by Conan-Kudo** [comment] 2019-02-08 14:49
I'm not sure this is a good idea or even needed to solve this problem. My understanding is that it is definitely possible to have libdnf or even base libsolv sort build dependencies and create ordered groups of packages to build correctly.

At least in my experience with OBS, the way it works is that the build scheduler uses the solver to identify what requires what and it creates order groups and processes them in a queue. If a dependency loop exists (package A requires package B which would would require package A after a build to build with more features) it does a second build and third build for that, and if the third build has the same digest (reproducibility-wise) as the second build, it's considered done.

So given a distribution package set, you'd wind up with cluster X, cluster Y, and cluster Z. Cluster X is required by cluster Y, which is required by cluster Z. So X would be built first, internally resolving itself, then Y, then Z.

This is what allows openSUSE to effectively be rebootstrapped entirely from scratch with minimal to no waste on a regular basis (as in more or less each month or something like that).

`mockchain` lacked integration with a solver, so it never was capable of that. Instead, you have to build everything and keep retrying until everything is built (assuming it can be built).

**Comment by sgallagher** [comment] 2019-02-26 21:23
> I'm not sure this is a good idea or even needed to solve this problem. My understanding is that it is definitely possible to have libdnf or even base libsolv sort build dependencies and create ordered groups of packages to build correctly.
> 
> At least in my experience with OBS, the way it works is that the build scheduler uses the solver to identify what requires what and it creates order groups and processes them in a queue. If a dependency loop exists (package A requires package B which would would require package A after a build to build with more features) it does a second build and third build for that, and if the third build has the same digest (reproducibility-wise) as the second build, it's considered done.
> 
> So given a distribution package set, you'd wind up with cluster X, cluster Y, and cluster Z. Cluster X is required by cluster Y, which is required by cluster Z. So X would be built first, internally resolving itself, then Y, then Z.
> 
> This is what allows openSUSE to effectively be rebootstrapped entirely from scratch with minimal to no waste on a regular basis (as in more or less each month or something like that).

Can you explain how OpenSUSE gets its initial package set without first rebuilding its source RPMs (or equivalent)? Do they just store all the SRPMs for each arch individually? In Fedora, we only keep one SRPM (from whichever arch randomly got picked for the BuildSRPMFromSCM step). We then rebuild it for each arch as part of the build step, to ensure we get the right dependencies. Every arch's sources repo just contains that hardlinked SRPM, rather than the arch-specific one, so we can't just process the repo's metadata to find out the buildrequires.

This is one of the difficulties we had back when we were trying to create a "base runtime" for Fedora. We had to keep a list of known "archful SRPMs", rebuild them and stick them in a local override repository so we could do dependency solving on them.

I suppose we could ask for rel-eng to create such a repo for each arch (non-mirrored), but I'm not sure that's our best option. Just adding a "buildafter" in the module definition seems like a large enough benefit for small enough effort to me.

**Comment by Conan-Kudo** [comment] 2019-02-26 22:59
> Can you explain how OpenSUSE gets its initial package set without first rebuilding its source RPMs (or equivalent)? Do they just store all the SRPMs for each arch individually?

I think the difference here is that openSUSE actually uses the raw spec file to identify build dependencies. `obs-build` can evaluate macros and platform conditions against a spec file, and parses the spec file to identify the correct build dependencies to emit and resolve with. It's not too hard to implement the same thing using rpm, either. I did a variation of this [for a project on GitLab.com](https://gitlab.com/datto/engineering/spacewalk-debian-client-packages/blob/master/.gitlab-ci/get-deb-buildreqs.sh) for being able to build the package in CI.

If you're using the spec file as the direct input rather than the source RPM, then you can evaluate all the platforms and determine the correct build dependencies without having to deal with the "archful SRPM" problem.

If you want to attempt this cheaply, use the [`rpmspec(8)`](https://www.mankier.com/8/rpmspec) tool to do it. You can also use the RPM Python API to do it, [as `dnf builddep` does](https://github.com/rpm-software-management/dnf-plugins-core/blob/db81b86858c20dc98aa0f33142eaef91f38edbb2/plugins/builddep.py#L190-L204). Since `rpmspec` accepts the global options that `rpm` does, you can use `--target` to make it pretend to be a specific arch for the purposes of determining build dependencies.

**Comment by contyk** [comment] 2019-03-11 13:24
Just so that we have it written somewhere...

We discussed the `buildafter` and the bootstrap mechanism at our hackfest last week and I think we could solve both of these use cases with adding just two keywords under the component name:

* `buildafter`, which specifies the key of the component that needs to be built before this one; the document must use either `buildafter` or `buildorder`, not both -- even though we could probably combine both mechanisms, I think it would be confusing
* `name`, which specifies the component name; normally the key is used as the name but if `name` is defined, it should be used instead, making it possible to build the same component more than once using arbitrary keys

Thus

```
components:
  rpms:
    foo:
      ref: foo
    bar:
      name: foo
      buildafter: foo
      ref: bar
```

would build the `foo` component twice from two different refs, the `bar` ref after the `foo` ref. There is a potential for an NVR conflict but I'd leave that to the packager.

**Comment by hanzz** [comment] 2019-03-12 12:19
Will also write summary of discussion we had about this topics on Friday:

- The `buildafter` as proposed here is not an issue for MBS. My plan so far is that we will *not* convert it to `buildorder` internally in MBS, but instead will really keep that buildafter info in MBS DB and use it to build components in right order. That means no more "batches" as we currently know them when buildorder is used..
- I think I'm against the combination of `buildafter` and `buildorder` unless the result of such combination is well defined in the specification itself. I don't want to invent the way how to handle that in MBS. Note that this would most likely make the MBS code more complex and it would take more time to implement this for no obvious benefit.
- The `name` looks like sane fix for bootstraping issue. Current MBS will have issue with this, because we kind of count that particular "package name" can appear in Module build just once and we will need to think about changing this, but I believe we will be able to remove that limitation. It's certainly easier to implement than other previously proposed ways how to handle bootstraping.

**Comment by sgallagher** [comment] 2019-03-12 12:23
> Will also write summary of discussion we had about this topics on Friday:
> 
> * The `buildafter` as proposed here is not an issue for MBS. My plan so far is that we will _not_ convert it to `buildorder` internally in MBS, but instead will really keep that buildafter info in MBS DB and use it to build components in right order. That means no more "batches" as we currently know them when buildorder is used..

:+1: 

> * I think I'm against the combination of `buildafter` and `buildorder` unless the result of such combination is well defined in the specification itself. I don't want to invent the way how to handle that in MBS. Note that this would most likely make the MBS code more complex and it would take more time to implement this for no obvious benefit.

Do you mean you'd prefer to drop `buildorder` entirely or you just want to be certain that you don't have a mixture of the two? If the latter, I can encode that into the `.validate()` routines in libmodulemd so that you will only have one or the other within a particular YAML document.

> * The `name` looks like sane fix for bootstraping issue. Current MBS will have issue with this, because we kind of count that particular "package name" can appear in Module build just once and we will need to think about changing this, but I believe we will be able to remove that limitation. It's certainly easier to implement than other previously proposed ways how to handle bootstraping.

I agree. The biggest issue I see is the possibility of having duplicate NEVRAs from the output. We may need to document how to avoid this (such as forbidding this by policy).

**Comment by hanzz** [comment] 2019-03-12 12:44
@sgallagher, I meant what @contyk wrote: `the document must use either buildafter or buildorder, not both`.

**Comment by sgallagher** [comment] 2019-03-12 12:46
OK, so I think we have consensus then that @contyk 's proposal for both `buildafter` and `name` makes sense, so I'll go ahead and getthat implemented in libmodulemd 2.2.0.

Thanks!

**Comment by sgallagher** [comment] 2019-03-12 13:36
Hmm, hang on. There is one problem with the proposed implementation above. I'm pretty sure we need to be able to indicate more than one dependency. So instead of `buildafter: foo`, I think we need:

```
components:
  rpms:
    foo:
      ref: foo
    bar:
      name: foo
      buildafter:
        - foo
      ref: bar
```
Changing the buildafter value to a list instead of a single item. @contyk, @hanzz do you agree?

**Comment by ignatenkobrain** [comment] 2019-03-12 13:47
oh right, fully agree!

**Comment by sgallagher** [comment] 2019-03-12 13:53
@contyk Regarding `name` vs. `key`, do we need to support this for all component types or just RPMs? I can make this change for just RPMs (or RPMs and modules) in the child class, but if we think we need to support it in all possible component types going forwards, it belongs in the parent class and would be an ABI break :(

**Comment by sgallagher** [comment] 2019-03-12 18:44
@contyk Another question on `name` vs `key`: If someone sets the name to be the same as the key (in the API), should we suppress the `name` field? I think the output is less confusing that way.

**Closed** 2019-03-20 16:34 UTC
Labels: SEMVER_MINOR
