### ISSUE TITLE
modulemd_module_dumps () Adds fields which where not initially present on the yaml document.

### ISSUE THREAD

**Issue by ipanova** [fedora-modularity/libmodulemd#76] opened 2018-07-20 14:09 UTC
```
In [1]: import gi

In [2]: gi.require_version('Modulemd', '1.0')

In [3]: from gi.repository import Modulemd

In [4]: x = '/home/ipanova/Downloads/fcb39b9a0b045c35442f1ab05dfd230148b4662fe1ab6ad7cd3e9722ffce8b84-modules.yaml'

In [5]: modules = Modulemd.objects_from_file(x)

In [6]: modules
Out[6]: 
[<Modulemd.Module object at 0x7fc91c111370 (ModulemdModule at 0x55f1aeadf040)>,
 <Modulemd.Module object at 0x7fc91c08d640 (ModulemdModule at 0x55f1aeadf130)>,
 <Modulemd.Module object at 0x7fc91c08d5f0 (ModulemdModule at 0x55f1aeadf220)>,
 <Modulemd.Module object at 0x7fc91c08d410 (ModulemdModule at 0x55f1aeadf310)>,
 <Modulemd.Module object at 0x7fc91c08d2d0 (ModulemdModule at 0x55f1aeadf400)>,
 <Modulemd.Defaults object at 0x7fc91c08d3c0 (ModulemdDefaults at 0x55f1aea3c280)>,
 <Modulemd.Defaults object at 0x7fc91c08d5a0 (ModulemdDefaults at 0x55f1aea3c2c0)>,
 <Modulemd.Defaults object at 0x7fc91c08d550 (ModulemdDefaults at 0x55f1aea3c300)>]

In [7]: module = modules[0]
In [8]: module.dump('/tmp/lal')

$ diff temp-django.yaml /tmp/lal
54a55,56
>   buildopts:
>     rpms: {}

```
Same behaviour is observed with dump() method.

Version: libmodulemd-1.5.2-1.fc28.x86_64

**Comment by sgallagher** [comment] 2018-07-20 14:30
Marking as a dupe of #75

**Closed** 2018-07-20 14:30 UTC
